import Colors from "@/constants/Colors";
import { defaultStyles } from "@/constants/Styles";
import { Ionicons } from "@expo/vector-icons";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Button,
  TouchableOpacity,
} from "react-native";
import { useHeaderHeight } from "@react-navigation/elements";

const Page = () => {
  const headerHeight = useHeaderHeight();

  return (
    <ScrollView
      style={{ backgroundColor: Colors.background }}
      contentContainerStyle={{
        paddingTop: headerHeight,
      }}
    >
      <Text style={[defaultStyles.sectionHeader, { color: "red" }]}>
        TTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTranransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactionsTransactions
      </Text>
    </ScrollView>
  );
};
const styles = StyleSheet.create({
  account: {
    margin: 80,
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 10,
  },
  balance: {
    fontSize: 50,
    fontWeight: "bold",
  },
  currency: {
    fontSize: 20,
    fontWeight: "500",
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
  },
  transactions: {
    marginHorizontal: 20,
    padding: 14,
    backgroundColor: "#fff",
    borderRadius: 16,
    gap: 20,
  },
  circle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.lightGray,
    justifyContent: "center",
    alignItems: "center",
  },
});
export default Page;
